# Generated by Django 2.0.3 on 2020-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiakkaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiakasnro', models.BigIntegerField(max_length=20)),
                ('sukunimi', models.CharField(max_length=100)),
                ('etunimi', models.CharField(max_length=100)),
                ('katuosoite', models.CharField(max_length=100)),
                ('postinumero', models.BigIntegerField(max_length=5)),
                ('postitmp', models.CharField(max_length=100)),
                ('puh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asiakkaat',
            },
        ),
    ]
